@extends('web.pages.page-article-layout')

@section('page-content')
    <article class="article-content">
        <h1>Виды укладок штучного паркета</h1>









<p style="text-align: center;">         <strong>КЛАССИЧЕСКИЕ РИСУНКИ УКЛАДКИ ИЗ ШТУЧНОГО ПАРКЕТА</strong>     </p>

<p style="text-align: center;"><span style="color: rgb(153, 51, 0);"><strong>
      <br></strong></span></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>РАЗБЕЖКА</strong></span>     </p>

<p><a href="/ukladka-shtuchnogo-parketa/">Укладка штучного паркета</a> рисунком<strong> разбежка</strong> (палуба), различается на:
  <br>
          а) симметричные, со сдвигом паркетных плашек на 1/3 длины или на 1/2 длины;
  <br>
          б) хаотичные – отсутствие симметрии.
  <br>
          Изменение угла наклона укладки и наличие разных <a href="/articles/shtuchnyy-parket/porody-dereva/">пород дерева</a> придает рисунку неповторимость.     </p>

<table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             01         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             02         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/разбежка (палуба) прямая, хаотичная" src="/storage/media/25/image001.png" border="0" alt="разбежка (палуба) прямая, хаотичная" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/разбежка (палуба) диагональная, хаотичная " src="/storage/media/26/image003.png" border="0" alt="разбежка (палуба) диагональная, хаотичная " width="224" height="224"></td>     </tr><tr style="text-align: center;"><td width="48%" valign="top">             разбежка (палуба) прямая, хаотичная<a href="/photos/razbezhka-paluba/"> Фото</a> <a href="/photos/parket-s-faskoy-delikatnaya-tsiklevka/">Фото</a>
        <br><br>
       _____         </td>         <td width="48%" height="0" valign="top">             разбежка (палуба) диагональная, хаотичная <a href="/photos/razbezhka-paluba/">Фото</a> <a href="/photos/evrotsiklevka-parketa-part2/">Фото</a> <a href="/photos/restavratsiya-parketa-buk-pod-maslom/">Фото</a>
        <br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             03         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             04         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/разбежка (палуба) прямая, сдвиг 1/3" src="/storage/media/27/image005.png" border="0" alt="разбежка (палуба) прямая, сдвиг 1/3" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/разбежка (палуба) диагональная, сдвиг1/3" src="/storage/media/28/image007.png" border="0" alt="разбежка (палуба) диагональная, сдвиг1/3" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             разбежка (палуба) прямая, сдвиг 1/3 <a href="/photos/razbezhka-paluba/">Фото</a> <a href="/photos/parket-s-faskoy-delikatnaya-tsiklevka/">Фото</a>
        <br><br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             разбежка (палуба) диагональная, сдвиг 1/3 <a href="/photos/evrotsiklevka-parketa-part2/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             05         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             06         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/разбежка (палуба) прямая, сдвиг 1/2" src="/storage/media/29/image009.png" border="0" alt="разбежка (палуба) прямая, сдвиг 1/2" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/разбежка (палуба) диагональная, сдвиг 1/2" src="/storage/media/30/image011.png" border="0" alt="разбежка (палуба) диагональная, сдвиг 1/2" width="225" height="226"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             разбежка (палуба) прямая, сдвиг 1/2 <a href="/photos/razbezhka-paluba/">Фото</a> <a href="/photos/tsiklevka-starogo-parketa/">Фото</a>
        <br><br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             разбежка (палуба) диагональная, сдвиг 1/2 <a href="/photos/ukladka-shtuchnogo-parketa-pletenka-paluba-yelochka/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             07         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             08         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/разбежка(палуба) двойная диагональная, хаотичная" src="/storage/media/31/image013.png" border="0" alt="разбежка(палуба) двойная диагональная, хаотичная" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/уклада лестница, две породы дерева" src="/storage/media/32/image015.png" border="0" alt="уклада лестница, две породы дерева" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             разбежка (палуба) двойная диагональная, хаотичная
        <br></td>         <td style="text-align: center;" width="48%" height="0" valign="top">             уклада лестница, две породы дерева
        <br><br></td>     </tr></tbody></table><p style="text-align: center;"><span style="color: rgb(153, 51, 0);"><strong>
      <br></strong></span></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>ЁЛОЧКА</strong></span>     </p>

<p>         Укладки <strong>ёлочка</strong> различаются на прямые и диагональные.
  <br>
          Присутствие разных пород дерева и различные форматы плашек придают рисунку неповторимость и позволяют увеличивать визуальные размеры помещения.     </p>

<table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             09         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             10         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка диагональная" src="/storage/media/33/image017.png" border="0" alt="ёлочка диагональная" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка прямая" src="/storage/media/34/image019.png" border="0" alt="ёлочка прямая" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка диагональная <a href="/photos/ukladka-shtuchnogo-parketa-pletenka-paluba-yelochka/">Фото</a>
        <br><br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка прямая <a href="/photos/remont-i-tsiklevka-parketa/">Фото</a> <a href="/photos/restavratsiya-parketa-dub-pod-maslom/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: left;" width="48%" valign="top">             11         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: left;" width="48%" height="21" valign="top">             12         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка двойная диагональная " src="/storage/media/35/image021.png" border="0" alt="ёлочка двойная диагональная " width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка двойная прямая" src="/storage/media/36/image023.png" border="0" alt="ёлочка двойная прямая" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка двойная диагональная <a href="/photos/osnovanie-po-reguliruemym-lagam-ukladka-dvoynaya-yelochka/">Фото</a>
        <br><br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка двойная прямая <a href="/photos/elochka-dvoynaya/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             13         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             14         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка тройная диагональная" src="/storage/media/37/image025.png" border="0" alt="ёлочка тройная диагональная" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка тройная прямая" src="/storage/media/38/image027.png" border="0" alt="ёлочка тройная прямая" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка тройная диагональная
        <br><br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка тройная прямая
        <br>
       _____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             15         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             16         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка четверная диагональная" src="/storage/media/39/image029.png" border="0" alt="ёлочка четверная диагональная" width="225" height="225"></td>         <td width="48%" height="231" valign="top">
        <p style="text-align: center;">                 <img longdesc="/ёлочка четверная прямая" src="/storage/media/40/image031.png" border="0" alt="ёлочка четверная прямая" width="225" height="225"></p>
               </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка четверная диагональная <a href="/photos/elochka-pyaternaya/">Фото</a>
        <br><br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка четверная прямая <a href="/photos/elochka-pyaternaya/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             17         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             18         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка двойная диагональная из разноформатного паркета" src="/storage/media/41/image033.png" border="0" alt="ёлочка двойная диагональная из разноформатного паркета" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка прямая из разноформатного паркета" src="/storage/media/42/image035.png" border="0" alt="ёлочка прямая из разноформатного паркета" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка двойная диагональная из разноформатного паркета
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка прямая из разноформатного паркета
        <br><br>
       _____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             19         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             20         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка из разноформатного паркета с пропорцией 1 к 3" src="/storage/media/43/image037.png" border="0" alt="ёлочка из разноформатного паркета с пропорцией 1 к 3" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка с пропорцией 1 к 3 из паркета одинакового формата " src="/storage/media/44/image039.png" border="0" alt="ёлочка с пропорцией 1 к 3 из паркета одинакового формата " width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка из разноформатного паркета с пропорцией 1 к 3
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка с пропорцией 1 к 3 из паркета одинакового формата
        <br>
       ____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             21         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             22         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка двойная диагональная из разных пород дерева" src="/storage/media/45/image041.png" border="0" alt="ёлочка двойная диагональная из разных пород дерева" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка диагональная из разных пород дерева" src="/storage/media/46/image043.png" border="0" alt="ёлочка диагональная из разных пород дерева" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка двойная диагональная из разных пород дерева
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка диагональная из разных пород дерева
        <br><br>
       _____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             23         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             24         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/ёлочка тройная диагональная из разных пород дерева " src="/storage/media/47/image045.png" border="0" alt="ёлочка тройная диагональная из разных пород дерева " width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/ёлочка &amp;laquo;французская&amp;raquo;" src="/storage/media/48/image047.png" border="0" alt="ёлочка &amp;laquo;французская&amp;raquo;" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             ёлочка тройная диагональная из разных пород дерева
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             ёлочка «французская»
        <br><br>
       _____</td>     </tr></tbody></table><p style="text-align: center;">
  <br></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>КВАДРАТЫ</strong></span>     </p>

<p>         Укладки <strong>квадрат</strong> различаются на прямые и диагональные, простые (вьетнамка) и сложные (колодец).
  <br>
          Присутствие разных пород дерева и декоративные вставки (бордюр, жилка и т.п.) создают красивый орнамент и придают рисунку неповторимость. <a href="/tsiklevka-parketa/">Циклевка паркета</a>, уложенного квадратом, позволяет придать помещению неповторимый вид.</p>

<table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             25         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             26         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат сложный диагональный из двух пород (дуб, красное дерево)" src="/storage/media/49/image049.png" border="0" alt="квадрат сложный диагональный из двух пород (дуб, красное дерево)" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат сложный прямой из двух пород (дуб, клен)" src="/storage/media/50/image051.png" border="0" alt="квадрат сложный прямой из двух пород (дуб, клен)" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат сложный диагональный из двух пород (дуб, красное дерево)<a href="/photos/evrotsiklevka-shlifovka-parketa/"> Фото</a>
        <br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат сложный прямой из двух пород (дуб, клен) <a href="/photos/evrotsiklevka-shlifovka-parketa/">Фото</a>
        <br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             27         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             28         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат двойной сложный прямой из двух пород дерева" src="/storage/media/51/image053.png" border="0" alt="квадрат двойной сложный прямой из двух пород дерева" width="225" height="226"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат двойной сложный диагональный из двух пород дерева " src="/storage/media/52/image055.png" border="0" alt="квадрат двойной сложный диагональный из двух пород дерева " width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат двойной сложный прямой из двух пород дерева <a href="/photos/evrotsiklevka-shlifovka-parketa/">Фото</a> <a href="/photos/evrotsiklevka-parketa/">Фото</a>
        <br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат двойной сложный диагональный из двух пород дерева <a href="/photos/evrotsiklevka-shlifovka-parketa/">Фото</a> <a href="/photos/evrotsiklevka-parketa/">Фото</a>
        <br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             29         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             30         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат сложный (колодец) из двух пород дерева с прожилками из клена" src="/storage/media/53/image057.png" border="0" alt="квадрат сложный (колодец) из двух пород дерева с прожилками из клена" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат тройной (художественный) из трех пород дерева" src="/storage/media/54/image059.png" border="0" alt="квадрат тройной (художественный) из трех пород дерева" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат сложный (колодец) из двух пород дерева с прожилками из клена 
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат тройной (художественный) из трех пород дерева
        <br>
       _____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             31         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             32         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат простой (вьетнамка) тройной диагональный" src="/storage/media/55/image061.png" border="0" alt="квадрат простой (вьетнамка) тройной диагональный" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат простой (вьетнамка) тройной" src="/storage/media/56/image063.png" border="0" alt="квадрат простой (вьетнамка) тройной" width="225" height="226"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат простой (вьетнамка) тройной диагональный <a href="/photos/khudozhestvennaya-ukladka-part2/">Фото</a>
        <br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат простой (вьетнамка) тройной <a href="/photos/khudozhestvennaya-ukladka-part2/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             33         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             34         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат простой (вьетнамка) четверной Диагональный" src="/storage/media/57/image065.png" border="0" alt="квадрат простой (вьетнамка) четверной Диагональный" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат простой (вьетнамка) четверной" src="/storage/media/58/image067.png" border="0" alt="квадрат простой (вьетнамка) четверной" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат простой (вьетнамка) четверной, диагональный <a href="/photos/khudozhestvennaya-ukladka-part2/">Фото</a>
        <br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат простой (вьетнамка) четверной <a href="/photos/khudozhestvennaya-ukladka-part2/">Фото</a>
        <br><br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             35         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             36         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/квадрат тройной диагональный с художественными вставками" src="/storage/media/59/image069.png" border="0" alt="квадрат тройной диагональный с художественными вставками" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/квадрат тройной прямой с художественными вставками" src="/storage/media/60/image071.png" border="0" alt="квадрат тройной прямой с художественными вставками" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             квадрат тройной диагональный с художественными вставками 
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             квадрат тройной прямой с художественными вставками
        <br>
       _____</td>     </tr></tbody></table><p style="text-align: center;">
  <br></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>ПЛЕТЕНКА</strong></span>     </p>

<p>         Укладки плетенка различаются на прямые и диагональные.
  <br>
          Присутствие разных пород дерева и различные форматы плашек придают рисунку неповторимость и позволяют увеличивать визуальные размеры помещения.</p>

<table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             37         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             38         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка из двух пород дерева дуб, клен " src="/storage/media/61/image073.png" border="0" alt="плетенка из двух пород дерева дуб, клен " width="225" height="226"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка из двух пород дерева дуб, красное дерево" src="/storage/media/62/image075.png" border="0" alt="плетенка из двух пород дерева дуб, красное дерево" width="225" height="225"></td>     </tr><tr style="text-align: center;"><td width="48%" valign="top">             плетенка из двух пород дерева дуб, клен 
        <br><br>
       _____</td>         <td width="48%" height="0" valign="top">             плетенка из двух пород дерева дуб, красное дерево <a href="/photos/pletenka-dvoynaya-troynaya-chetvernaya/">Фото</a>
        <br>
       _____         </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             39         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             40         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка двойная из двух пород дерева дуб, красное дерево " src="/storage/media/63/image077.png" border="0" alt="плетенка двойная из двух пород дерева дуб, красное дерево " width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка двойная из двух пород дерева дуб, клен" src="/storage/media/64/image079.png" border="0" alt=" плетенка двойная из двух пород дерева дуб, клен" width="225" height="224"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             плетенка двойная из двух пород дерева дуб, красное дерево <a href="/photos/pletenka-dvoynaya-troynaya-chetvernaya/">Фото</a>
        <br>
       _____         </td>         <td style="text-align: center;" width="48%" height="0" valign="top">             плетенка двойная из двух пород дерева дуб, клен 
        <br>
       _____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             41         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             42         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка тройная из двух пород дерева дуб, клен" src="/storage/media/65/image081.png" border="0" alt="плетенка тройная из двух пород дерева дуб, клен" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка тройная из двух пород дерева дуб, красное дерево" src="/storage/media/66/image083.png" border="0" alt="плетенка тройная из двух пород дерева дуб, красное дерево" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             плетенка тройная из двух пород дерева  дуб, клен 
        <br><br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             плетенка тройная из двух пород дерева дуб, красное дерево
        <br><br>
       ____</td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             43         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             44         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка четверная из двух пород дерева дуб, красное дерево" src="/storage/media/67/image085.png" border="0" alt="плетенка четверная из двух пород дерева дуб, красное дерево" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка четверная из двух пород дерева дуб, клен" src="/storage/media/68/image087.png" border="0" alt="плетенка четверная из двух пород дерева дуб, клен" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             плетенка четверная из двух пород дерева дуб, красное дерево <a href="/photos/ukladka-shtuchnogo-parketa-pletenka-paluba-yelochka/%0D%0A">Фото</a> 
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             плетенка четверная из двух пород дерева дуб, клен
        <br>
       _____ </td>     </tr></tbody></table><table style="height: 252px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             45         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             46         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка двойная из разноформатного паркета, две породы дерева" src="/storage/media/69/image089.png" border="0" alt="плетенка двойная из разноформатного паркета, две породы дерева" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка (пропорция 2 к 3) из двух пород дерева" src="/storage/media/70/image091.png" border="0" alt="плетенка (пропорция 2 к 3) из двух пород дерева" width="225" height="224"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             плетенка двойная из разноформатного паркета, две породы дерева 
        <br>
       _____</td>         <td style="text-align: center;" width="48%" height="0" valign="top">             плетенка (пропорция 2 к 3) из двух пород дерева 
        <br>
       _____</td>     </tr></tbody></table><table style="height: 274px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top">             47         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td width="48%" height="21" valign="top">             47         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/плетенка (пропорция 3 к 2) " src="/storage/media/71/image093.png" border="0" alt="плетенка (пропорция 3 к 2) " width="225" height="239"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/плетенка (пропорция 2 к 1) из двух пород дерева" src="/storage/media/72/image095.png" border="0" alt="плетенка (пропорция 2 к 1) из двух пород дерева" width="225" height="225"></td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             плетенка (пропорция 3 к 2) <a href="/photos/pletenka-2k1-raznoformatnaya/">Фото</a>
        <br><br><br></td>         <td style="text-align: center;" width="48%" height="0" valign="top">             плетенка (пропорция 2 к 1) из двух пород дерева <a href="/photos/pletenka-2k1-raznoformatnaya/">Фото</a>
        <br><br><br></td>     </tr></tbody></table><p style="text-align: center;">
  <br></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>ФРИЗ </strong>
    <br></span></p>

<p>         <strong>Фриз</strong> – это декоративный элемент паркетной укладки. Фриз обрамляет периметр паркетного ковра, придавая ему завершенный вид, сглаживает конструктивные неточности или отступления от симметрии в помещении. <span style="text-align: center;">(</span><a href="/photos/bordyur/">Фото</a><span style="text-align: center;">)</span></p>

<table style="height: 274px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: center;" width="48%" valign="top">             49         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: center;" width="48%" height="21" valign="top">             50         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img src="/storage/media/73/image097.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img src="/storage/media/74/image099.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>     </tr><tr><td width="48%" align="left" valign="top">
        <br><div style="text-align: center;">
          <br></div>
       </td>         <td width="48%" height="0" valign="top" style="text-align: center;">
        <br><br><br></td>     </tr></tbody></table><table style="height: 274px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: center;" width="48%" valign="top">             51         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: center;" width="48%" height="21" valign="top">             52         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img src="/storage/media/75/image101.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img src="/storage/media/76/image103.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>     </tr><tr><td width="48%" align="left" valign="top"></td>         <td width="48%" height="0" valign="top"></td>     </tr></tbody></table><p style="text-align: center;"> _____ </p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>РИСУНОК УКЛАДКИ ФРИЗА В УГЛУ</strong></span>     </p>

<table style="height: 274px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: center;" width="48%" valign="top">             53         </td>         <td rowspan="3" width="20" valign="top"></td>         <td rowspan="3" width="20" valign="top"></td>         <td style="text-align: center;" width="48%" height="21" valign="top">             54         </td>     </tr><tr><td style="text-align: center;" width="48%" valign="top">             <img longdesc="/РИСУНОК УКЛАДКИ ФРИЗА В УГЛУ" src="/storage/media/77/image105.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>         <td style="text-align: center;" width="48%" height="231" valign="top">             <img longdesc="/РИСУНОК УКЛАДКИ ФРИЗА В УГЛУ" src="/storage/media/78/image107.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></td>     </tr><tr><td width="48%" align="left" valign="top"></td>         <td width="48%" height="0" valign="top"></td>     </tr></tbody></table><p style="text-align: center;">
  <br></p>

<p style="text-align: center;">         55     </p>

<p style="text-align: center;">         <img longdesc="/РИСУНОК УКЛАДКИ ФРИЗА В УГЛУ" src="/storage/media/79/image109.png" border="0" alt="Фриз – это декоративный элемент паркетной укладки" width="225" height="225"></p>

<p style="text-align: center;">_____</p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>ХУДОЖЕСТВЕННЫЙ ПАРКЕТ </strong></span>     </p>

<p style="text-align: center;">         <strong><span style="color: rgb(0, 0, 0);">бордюр</span></strong><strong><span style="color: rgb(0, 0, 0);"> 
      <br></span></strong>     </p>

<p>         <strong>Паркетный бордюр</strong> – это художественно-декоративный элемент паркетного пола в виде мозаичной полосы. Обычно обрамляет периметр основного паркетного ковра, придавая ему завершенный вид, сглаживает конструктивные неточности и отступления от симметрии в помещении.
  <br>
          Бордюр используется во внутренних зонах паркетного пола, с целью выделения определенных участков или для визуального разделения помещения на зоны. Варьируя шириной и расположением паркетного бордюра, можно влиять на зрительное восприятие паркетного пола. </p>

<table border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/80/image111.jpg" border="0" alt="Паркетный бордюр" width="134" height="134"></td>         <td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/81/image113.jpg" border="0" alt="Паркетный бордюр" width="134" height="134"></td>         <td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/82/image115.jpg" border="0" alt="Паркетный бордюр" width="134" height="134"></td>     </tr></tbody></table><p style="text-align: center;"><span style="color: rgb(153, 51, 0);"><strong>
      <br></strong></span></p>

<p style="text-align: center;">         <strong>розетка</strong>
  <br></p>

<p>         <strong>Розетка</strong> – это элемент художественного паркета, выполненный в виде декоративной композиции с использованием нескольких ценных пород древесины. <a href="/tonirovanie-parketa/">Тонировка художественного паркета</a> обычно не требуется, в составе розетки уже есть древесина всех расцветок. Обычно розетка имеет форму круга или овала, но могут быть и другие формы. <span style="text-align: center;">(</span><a href="/photos/parketnaya-rozetka/">Фото</a><span style="text-align: center;">)</span></p>

<table border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/83/image117.jpg" border="0" alt="Розетка – это элемент художественного паркета" width="153" height="153"></td>         <td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/84/image119.jpg" border="0" alt="Розетка – это элемент художественного паркета" width="153" height="153"></td>         <td style="text-align: center;" width="33%" height="133">             <img src="/storage/media/85/image121.jpg" border="0" alt="Розетка – это элемент художественного паркета" width="153" height="153"></td>     </tr></tbody></table><p style="text-align: center;">         <strong>
    <br>
            инкрустированный паркет</strong></p>

<p>         <strong>Инкрустированный паркет</strong> – недорогая альтернатива художественному паркету. (<a href="/photos/ukladka-khudozhestvennogo-parketa-bez-fanery-na-multimoll/">фото</a>)
  <br>
          Использование инкрустированных планок при укладке штучного паркета позволяет простыми способами создавать на полу различные художественные композиции.
  <br>
          Заказав всего 10-15 инкрустированных планок на любой вкус, и используя обычный штучный паркет, можно легко создать современный художественный паркетный пол без особых затрат!
  <br>
          В качестве основы используется планка стандартного штучного паркета. В нее, на всю толщину паркетной планки врезаются детали композиции, изготовленные из других пород древесины.     </p>

<p style="text-align: center;">         <img longdesc="/ИНКРУСТИРОВАННЫЙ ПАРКЕТ" src="/storage/media/86/image123.jpg" border="0" alt="ИНКРУСТИРОВАННЫЙ ПАРКЕТ" width="200" height="30"><img longdesc="/ИНКРУСТИРОВАННЫЙ ПАРКЕТ" src="/storage/media/87/image125.jpg" border="0" alt="ИНКРУСТИРОВАННЫЙ ПАРКЕТ" width="200" height="30"><img longdesc="/ИНКРУСТИРОВАННЫЙ ПАРКЕТ" src="/storage/media/88/image127.jpg" border="0" alt="ИНКРУСТИРОВАННЫЙ ПАРКЕТ" width="200" height="30"></p>

<p style="text-align: center;">         <img longdesc="/ИНКРУСТИРОВАННЫЙ ПАРКЕТ" src="/storage/media/89/image129.jpg" border="0" alt="ИНКРУСТИРОВАННЫЙ ПАРКЕТ" width="220" height="66"><img longdesc="/ИНКРУСТИРОВАННЫЙ ПАРКЕТ" src="/storage/media/90/image131.jpg" border="0" alt="ИНКРУСТИРОВАННЫЙ ПАРКЕТ" width="220" height="64"></p>

<p style="text-align: center;"><span style="color: rgb(153, 51, 0);"><strong>
      <br></strong></span></p>

<p style="text-align: center;">         <span style="color: rgb(153, 51, 0);"><strong>
      <br>
              МОДУЛЬНЫЙ ПАРКЕТ</strong></span>     </p>

<p>         <strong>Модульный (щитовой паркет)</strong> – это художественный паркет, рисунок которого состоит из повторяющихся модулей, изготовленных в производственных условиях. На объекте происходит только сборка общего орнамента пола из заранее приготовленных щитов. (<a href="/photos/ukladka-khudozhestvennogo-parketa-bez-fanery-na-multimoll/">фото</a>)     </p>

<table style="height: 196px;" border="0" cellspacing="0" cellpadding="0" width="100%"><tbody><tr><td width="48%" align="left" valign="top"></td>         <td rowspan="2" width="20" valign="top"></td>         <td rowspan="2" width="20" valign="top"></td>         <td width="48%" height="21" valign="top"></td>     </tr><tr><td width="48%" align="left" valign="top" style="text-align: center;">             <img longdesc="/Модульный (щитовой паркет)" src="/storage/media/91/image132.jpg" border="0" alt="Модульный (щитовой паркет)" width="220" height="220"></td>         <td width="48%" valign="top" style="text-align: center;">             <img longdesc="/Модульный (щитовой паркет)" src="/storage/media/92/image134.jpg" border="0" alt="Модульный (щитовой паркет)" width="220" height="220"></td>     </tr></tbody></table><font size="1"> 22.07.15</font>

                </article>
@endsection
