name: Run Tests

on:
    - push

jobs:
    phpunit:
        name: Run Tests
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: 'true'

            -   name: Display Docker Version
                run: |
                    docker -v
                    docker-compose -v

            -   name: Create .env
                run: cp .env.example .env

            -   name: Run Docker Compose
                run: docker-compose -f docker-compose.ci.yml up -d --build

            -   name: Install Composer Dependencies In Docker Container
                run: docker-compose exec -T app composer install -n --prefer-dist

            -   name: Generate Key
                run: docker-compose exec -T app php artisan key:generate

            -   name: Display Docker Php Info
                run: docker-compose exec -T app php -i

            -   name: Run Php Artisan Test
                # -T option because of https://github.com/docker/compose/issues/7306#issuecomment-602163499
                run: docker-compose exec -T app php artisan test
